version: '3.8'
services:
  factory:
    build: .
    ports:
      - "3000:3000"
    volumes:
      # This links THEIR folders to the DOCKER folders
      - ./input:/usr/src/app/input
      - ./output:/usr/src/app/output
    restart: always